import {
  createCategoryIndex,
  createContentItems,
  type ContentItem,
} from "@/lib/content";

export type AffirmationCategory =
  | "self-discipline"
  | "faith"
  | "abundance"
  | "healing"
  | "confidence"
  | "focus"
  | "peace";

const stemsByCategory: Record<AffirmationCategory, string[]> = {
  "self-discipline": [
    "I honor my purpose by choosing the next right action.",
    "I keep my promises to myself with patience and strength.",
    "Small faithful steps are shaping a disciplined life in me.",
    "I do what matters before I chase what distracts me.",
    "My habits are becoming servants of my purpose.",
    "I can begin again without shame and continue with wisdom.",
    "Discipline is not pressure; it is devotion in motion.",
    "I choose structure because my calling deserves support.",
    "I follow through even when my feelings move slowly.",
    "Every focused action strengthens the person I am becoming.",
    "I am steady, prepared, and willing to grow.",
    "I use my time with intention and gratitude.",
    "I release excuses and receive the strength to act.",
    "My future is built by the faithful choices I make today.",
    "I can be consistent without being harsh with myself.",
    "I train my mind to return to what matters.",
    "I am not ruled by impulse; I am led by purpose.",
    "Progress is welcome here, even when it arrives quietly.",
    "I show up for my assignment with courage and care.",
    "My daily rhythm is becoming stronger, clearer, and wiser.",
    "I choose preparation over procrastination.",
    "God gives me strength to finish what wisdom asks me to start.",
  ],
  faith: [
    "I walk forward trusting that God is already present.",
    "My faith is stronger than the fear trying to lead me.",
    "I do not need every answer to take the next faithful step.",
    "God is guiding me with wisdom, timing, and grace.",
    "I can rest because I am held by more than my own strength.",
    "My spirit is anchored in truth, not in temporary feelings.",
    "I trust the process because God is working in the unseen.",
    "Faith rises in me as I remember what God has already done.",
    "I am not forgotten, overlooked, or abandoned.",
    "God can use this season to grow strength in me.",
    "I move with hope because grace is meeting me here.",
    "I choose belief over panic and prayer over pressure.",
    "My steps are ordered even when the path feels quiet.",
    "I am learning to trust without needing to control everything.",
    "God's peace is available to me in this exact moment.",
    "I am becoming more rooted, more patient, and more faithful.",
    "What is for me can arrive in God's timing.",
    "I release the need to force what God can open.",
    "My faith makes room for courage, patience, and obedience.",
    "I am covered by grace while I grow.",
    "I can believe again, hope again, and begin again.",
    "God is faithful in details I cannot yet see.",
  ],
  abundance: [
    "I welcome provision with wisdom, gratitude, and responsibility.",
    "Abundance flows through the value I create and the faith I practice.",
    "I am open to opportunities that align with purpose and peace.",
    "I can receive more without losing humility.",
    "My gifts are worthy of stewardship, growth, and reward.",
    "I think in possibility while acting with discipline.",
    "I release scarcity and practice wise expectation.",
    "Money is a tool I can manage with clarity and generosity.",
    "I am becoming a faithful steward of increase.",
    "New doors can open as I prepare with excellence.",
    "I can build wealth with integrity, patience, and wisdom.",
    "Provision can reach me through ideas, relationships, and service.",
    "I expect good things and prepare my life to hold them well.",
    "My work carries value, and I receive value in return.",
    "I am learning to multiply what has been placed in my hands.",
    "I release shame around receiving and choose grateful responsibility.",
    "Abundance begins with a renewed mind and faithful action.",
    "I am not limited by old patterns of lack.",
    "I can be generous because I trust the Source beyond the resource.",
    "My financial life is becoming ordered, peaceful, and fruitful.",
    "I make room for increase by practicing wisdom today.",
    "I am available for better opportunities and prepared for them.",
  ],
  healing: [
    "Healing is unfolding in me with grace, patience, and truth.",
    "I allow God to restore the places I could not fix alone.",
    "My heart can soften without losing its strength.",
    "I release what wounded me and receive what will rebuild me.",
    "I am not the pain I survived; I am the life still growing.",
    "Peace is returning to the rooms inside me.",
    "I can heal at the pace my soul can hold.",
    "God is near to every tender place in me.",
    "I choose restoration over resentment.",
    "My story is still being redeemed with wisdom and love.",
    "I breathe out old heaviness and breathe in new mercy.",
    "I am allowed to be whole, joyful, and free.",
    "What broke my heart does not get to define my future.",
    "I receive courage to face what needs healing.",
    "I am becoming kinder to the parts of me that are still recovering.",
    "God can bring beauty from seasons I did not understand.",
    "I release the burden of pretending I am untouched.",
    "My body, mind, and spirit are worthy of care.",
    "Healing is not weakness; it is holy repair.",
    "I am safe to grow beyond survival.",
    "Grace meets me in the process, not only at the finish line.",
    "I welcome restoration, renewal, and a lighter heart.",
  ],
  confidence: [
    "I stand with quiet confidence because God has equipped me.",
    "I am allowed to take up space with humility and strength.",
    "My voice has purpose, and I can use it with wisdom.",
    "I do not shrink to make fear comfortable.",
    "I carry value before anyone validates it.",
    "I can learn, improve, and still show up boldly.",
    "Confidence grows each time I act from truth.",
    "I am not behind; I am being developed.",
    "I can be seen without being perfect.",
    "My courage is becoming stronger than my self-doubt.",
    "I trust the gifts God placed inside me.",
    "I do not need comparison to measure my worth.",
    "I bring preparation, presence, and purpose into every room.",
    "I can try again with more wisdom than before.",
    "My identity is deeper than criticism or applause.",
    "I am capable of hard things and worthy of good things.",
    "I choose bold obedience over quiet fear.",
    "I am becoming more secure in who I am.",
    "My confidence is rooted in truth, not performance.",
    "I can lead, create, speak, and serve with courage.",
    "I release the fear of being misunderstood.",
    "I walk in the strength of who God is making me.",
  ],
  focus: [
    "My attention is a gift, and I direct it with wisdom.",
    "I return to the present moment with clarity and calm.",
    "I can choose one meaningful task and give it my best.",
    "Distraction loses power when purpose becomes clear.",
    "I make space for deep work and faithful progress.",
    "My mind is becoming clearer, steadier, and more ordered.",
    "I release mental clutter and receive direction.",
    "I can pause, breathe, and begin again.",
    "Focus is available to me one choice at a time.",
    "I protect my attention from what does not serve my calling.",
    "I am fully present for the work in front of me.",
    "I move with intention instead of rushing in circles.",
    "My priorities are becoming clear and actionable.",
    "I can finish the next step without carrying the whole mountain.",
    "I give my energy to what produces peace and progress.",
    "My thoughts can be trained toward truth and purpose.",
    "I simplify my day and strengthen my results.",
    "I am not scattered; I am being gathered.",
    "I choose clarity over noise.",
    "I can work with patience, excellence, and flow.",
    "My focus increases as I honor my limits.",
    "I am guided toward what deserves my attention.",
  ],
  peace: [
    "Peace is allowed to live in me today.",
    "I can be calm without having every detail solved.",
    "God's presence steadies me from the inside out.",
    "I release the urge to carry what was never mine.",
    "My breath can slow, my shoulders can soften, and my heart can rest.",
    "I choose peace without surrendering my purpose.",
    "Stillness is not wasted; it is where I am restored.",
    "I do not have to match the chaos around me.",
    "My mind is returning to quiet trust.",
    "I am safe to pause and let grace meet me.",
    "Peace begins with one surrendered thought.",
    "I can respond with wisdom instead of reacting from fear.",
    "My spirit is anchored even when circumstances shift.",
    "I welcome calm, patience, and holy perspective.",
    "I let go of what I cannot control and honor what I can.",
    "Peace is stronger than the pressure of this moment.",
    "I am learning to live from rest, not from panic.",
    "I choose a quiet mind and a faithful heart.",
  ],
};

export const affirmations = createContentItems(stemsByCategory, [
  "affirmation",
  "mindset",
]) as ContentItem[];

export const affirmationsByCategory = createCategoryIndex(affirmations);
