import { createCategoryIndex, type BibleVerseItem } from "@/lib/content";

export const bibleVerses: BibleVerseItem[] = [
  { text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God.", category: "anxiety", reference: "Philippians 4:6", tags: ["anxiety", "kjv"] },
  { text: "Casting all your care upon him; for he careth for you.", category: "anxiety", reference: "1 Peter 5:7", tags: ["anxiety", "kjv"] },
  { text: "In the multitude of my thoughts within me thy comforts delight my soul.", category: "anxiety", reference: "Psalm 94:19", tags: ["anxiety", "kjv"] },
  { text: "Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself. Sufficient unto the day [is] the evil thereof.", category: "anxiety", reference: "Matthew 6:34", tags: ["anxiety", "kjv"] },
  { text: "Let not your heart be troubled: ye believe in God, believe also in me.", category: "anxiety", reference: "John 14:1", tags: ["anxiety", "kjv"] },
  { text: "Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer the righteous to be moved.", category: "anxiety", reference: "Psalm 55:22", tags: ["anxiety", "kjv"] },
  { text: "Heaviness in the heart of man maketh it stoop: but a good word maketh it glad.", category: "anxiety", reference: "Proverbs 12:25", tags: ["anxiety", "kjv"] },
  { text: "I sought the LORD, and he heard me, and delivered me from all my fears.", category: "anxiety", reference: "Psalm 34:4", tags: ["anxiety", "kjv"] },
  { text: "What time I am afraid, I will trust in thee.", category: "anxiety", reference: "Psalm 56:3", tags: ["anxiety", "kjv"] },
  { text: "From the end of the earth will I cry unto thee, when my heart is overwhelmed: lead me to the rock [that] is higher than I.", category: "anxiety", reference: "Psalm 61:2", tags: ["anxiety", "kjv"] },
  { text: "I will lift up mine eyes unto the hills, from whence cometh my help.", category: "anxiety", reference: "Psalm 121:1", tags: ["anxiety", "kjv"] },
  { text: "My help [cometh] from the LORD, which made heaven and earth.", category: "anxiety", reference: "Psalm 121:2", tags: ["anxiety", "kjv"] },
  { text: "Thou wilt keep [him] in perfect peace, [whose] mind [is] stayed [on thee]: because he trusteth in thee.", category: "anxiety", reference: "Isaiah 26:3", tags: ["anxiety", "kjv"] },
  { text: "Come unto me, all [ye] that labour and are heavy laden, and I will give you rest.", category: "anxiety", reference: "Matthew 11:28", tags: ["anxiety", "kjv"] },
  { text: "Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and ye shall find rest unto your souls.", category: "anxiety", reference: "Matthew 11:29", tags: ["anxiety", "kjv"] },
  { text: "Fear not, little flock; for it is your Father's good pleasure to give you the kingdom.", category: "anxiety", reference: "Luke 12:32", tags: ["anxiety", "kjv"] },
  { text: "I can do all things through Christ which strengtheneth me.", category: "strength", reference: "Philippians 4:13", tags: ["strength", "kjv"] },
  { text: "He giveth power to the faint; and to [them that have] no might he increaseth strength.", category: "strength", reference: "Isaiah 40:29", tags: ["strength", "kjv"] },
  { text: "But they that wait upon the LORD shall renew [their] strength; they shall mount up with wings as eagles; they shall run, and not be weary; [and] they shall walk, and not faint.", category: "strength", reference: "Isaiah 40:31", tags: ["strength", "kjv"] },
  { text: "God [is] our refuge and strength, a very present help in trouble.", category: "strength", reference: "Psalm 46:1", tags: ["strength", "kjv"] },
  { text: "The LORD [is] my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and the horn of my salvation, [and] my high tower.", category: "strength", reference: "Psalm 18:2", tags: ["strength", "kjv"] },
  { text: "The LORD [is] my light and my salvation; whom shall I fear? the LORD [is] the strength of my life; of whom shall I be afraid?", category: "strength", reference: "Psalm 27:1", tags: ["strength", "kjv"] },
  { text: "The LORD [is] my strength and my shield; my heart trusted in him, and I am helped: therefore my heart greatly rejoiceth; and with my song will I praise him.", category: "strength", reference: "Psalm 28:7", tags: ["strength", "kjv"] },
  { text: "The LORD will give strength unto his people; the LORD will bless his people with peace.", category: "strength", reference: "Psalm 29:11", tags: ["strength", "kjv"] },
  { text: "My flesh and my heart faileth: [but] God [is] the strength of my heart, and my portion for ever.", category: "strength", reference: "Psalm 73:26", tags: ["strength", "kjv"] },
  { text: "Finally, my brethren, be strong in the Lord, and in the power of his might.", category: "strength", reference: "Ephesians 6:10", tags: ["strength", "kjv"] },
  { text: "Then he said unto them, Go your way, eat the fat, and drink the sweet, and send portions unto them for whom nothing is prepared: for [this] day [is] holy unto our Lord: neither be ye sorry; for the joy of the LORD is your strength.", category: "strength", reference: "Nehemiah 8:10", tags: ["strength", "kjv"] },
  { text: "The LORD [is] my strength and song, and he is become my salvation: he [is] my God, and I will prepare him an habitation; my father's God, and I will exalt him.", category: "strength", reference: "Exodus 15:2", tags: ["strength", "kjv"] },
  { text: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God [is] with thee whithersoever thou goest.", category: "strength", reference: "Joshua 1:9", tags: ["strength", "kjv"] },
  { text: "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me.", category: "strength", reference: "2 Corinthians 12:9", tags: ["strength", "kjv"] },
  { text: "Therefore I take pleasure in infirmities, in reproaches, in necessities, in persecutions, in distresses for Christ's sake: for when I am weak, then am I strong.", category: "strength", reference: "2 Corinthians 12:10", tags: ["strength", "kjv"] },
  { text: "The LORD God [is] my strength, and he will make my feet like hinds' [feet], and he will make me to walk upon mine high places. To the chief singer on my stringed instruments.", category: "strength", reference: "Habakkuk 3:19", tags: ["strength", "kjv"] },
  { text: "The LORD [is] my strength and song, and is become my salvation.", category: "strength", reference: "Psalm 118:14", tags: ["strength", "kjv"] },
  { text: "Now faith is the substance of things hoped for, the evidence of things not seen.", category: "faith", reference: "Hebrews 11:1", tags: ["faith", "kjv"] },
  { text: "So then faith [cometh] by hearing, and hearing by the word of God.", category: "faith", reference: "Romans 10:17", tags: ["faith", "kjv"] },
  { text: "(For we walk by faith, not by sight:)", category: "faith", reference: "2 Corinthians 5:7", tags: ["faith", "kjv"] },
  { text: "Therefore I say unto you, What things soever ye desire, when ye pray, believe that ye receive [them], and ye shall have [them].", category: "faith", reference: "Mark 11:24", tags: ["faith", "kjv"] },
  { text: "And Jesus said unto them, Because of your unbelief: for verily I say unto you, If ye have faith as a grain of mustard seed, ye shall say unto this mountain, Remove hence to yonder place; and it shall remove; and nothing shall be impossible unto you.", category: "faith", reference: "Matthew 17:20", tags: ["faith", "kjv"] },
  { text: "But without faith [it is] impossible to please [him]: for he that cometh to God must believe that he is, and [that] he is a rewarder of them that diligently seek him.", category: "faith", reference: "Hebrews 11:6", tags: ["faith", "kjv"] },
  { text: "But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed.", category: "faith", reference: "James 1:6", tags: ["faith", "kjv"] },
  { text: "Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through the power of the Holy Ghost.", category: "faith", reference: "Romans 15:13", tags: ["faith", "kjv"] },
  { text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding.", category: "faith", reference: "Proverbs 3:5", tags: ["faith", "kjv"] },
  { text: "In all thy ways acknowledge him, and he shall direct thy paths.", category: "faith", reference: "Proverbs 3:6", tags: ["faith", "kjv"] },
  { text: "Commit thy way unto the LORD; trust also in him; and he shall bring [it] to pass.", category: "faith", reference: "Psalm 37:5", tags: ["faith", "kjv"] },
  { text: "Rest in the LORD, and wait patiently for him: fret not thyself because of him who prospereth in his way, because of the man who bringeth wicked devices to pass.", category: "faith", reference: "Psalm 37:7", tags: ["faith", "kjv"] },
  { text: "Blessed [is] the man that trusteth in the LORD, and whose hope the LORD is.", category: "faith", reference: "Jeremiah 17:7", tags: ["faith", "kjv"] },
  { text: "For he shall be as a tree planted by the waters, and [that] spreadeth out her roots by the river, and shall not see when heat cometh, but her leaf shall be green; and shall not be careful in the year of drought, neither shall cease from yielding fruit.", category: "faith", reference: "Jeremiah 17:8", tags: ["faith", "kjv"] },
  { text: "I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me: and the life which I now live in the flesh I live by the faith of the Son of God, who loved me, and gave himself for me.", category: "faith", reference: "Galatians 2:20", tags: ["faith", "kjv"] },
  { text: "For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, [even] our faith.", category: "faith", reference: "1 John 5:4", tags: ["faith", "kjv"] },
  { text: "For by grace are ye saved through faith; and that not of yourselves: [it is] the gift of God:", category: "faith", reference: "Ephesians 2:8", tags: ["faith", "kjv"] },
  { text: "Heal me, O LORD, and I shall be healed; save me, and I shall be saved: for thou [art] my praise.", category: "healing", reference: "Jeremiah 17:14", tags: ["healing", "kjv"] },
  { text: "He healeth the broken in heart, and bindeth up their wounds.", category: "healing", reference: "Psalm 147:3", tags: ["healing", "kjv"] },
  { text: "But he [was] wounded for our transgressions, [he was] bruised for our iniquities: the chastisement of our peace [was] upon him; and with his stripes we are healed.", category: "healing", reference: "Isaiah 53:5", tags: ["healing", "kjv"] },
  { text: "Bless the LORD, O my soul, and forget not all his benefits:", category: "healing", reference: "Psalm 103:2", tags: ["healing", "kjv"] },
  { text: "Who forgiveth all thine iniquities; who healeth all thy diseases;", category: "healing", reference: "Psalm 103:3", tags: ["healing", "kjv"] },
  { text: "O LORD my God, I cried unto thee, and thou hast healed me.", category: "healing", reference: "Psalm 30:2", tags: ["healing", "kjv"] },
  { text: "A merry heart doeth good [like] a medicine: but a broken spirit drieth the bones.", category: "healing", reference: "Proverbs 17:22", tags: ["healing", "kjv"] },
  { text: "And the prayer of faith shall save the sick, and the Lord shall raise him up; and if he have committed sins, they shall be forgiven him.", category: "healing", reference: "James 5:15", tags: ["healing", "kjv"] },
  { text: "Confess [your] faults one to another, and pray one for another, that ye may be healed. The effectual fervent prayer of a righteous man availeth much.", category: "healing", reference: "James 5:16", tags: ["healing", "kjv"] },
  { text: "And said, If thou wilt diligently hearken to the voice of the LORD thy God, and wilt do that which is right in his sight, and wilt give ear to his commandments, and keep all his statutes, I will put none of these diseases upon thee, which I have brought upon the Egyptians: for I [am] the LORD that healeth thee.", category: "healing", reference: "Exodus 15:26", tags: ["healing", "kjv"] },
  { text: "The LORD will strengthen him upon the bed of languishing: thou wilt make all his bed in his sickness.", category: "healing", reference: "Psalm 41:3", tags: ["healing", "kjv"] },
  { text: "He sent his word, and healed them, and delivered [them] from their destructions.", category: "healing", reference: "Psalm 107:20", tags: ["healing", "kjv"] },
  { text: "But unto you that fear my name shall the Sun of righteousness arise with healing in his wings; and ye shall go forth, and grow up as calves of the stall.", category: "healing", reference: "Malachi 4:2", tags: ["healing", "kjv"] },
  { text: "But Jesus turned him about, and when he saw her, he said, Daughter, be of good comfort; thy faith hath made thee whole. And the woman was made whole from that hour.", category: "healing", reference: "Matthew 9:22", tags: ["healing", "kjv"] },
  { text: "And he said unto her, Daughter, thy faith hath made thee whole; go in peace, and be whole of thy plague.", category: "healing", reference: "Mark 5:34", tags: ["healing", "kjv"] },
  { text: "And he said unto her, Daughter, be of good comfort: thy faith hath made thee whole; go in peace.", category: "healing", reference: "Luke 8:48", tags: ["healing", "kjv"] },
  { text: "Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul prospereth.", category: "healing", reference: "3 John 1:2", tags: ["healing", "kjv"] },
  { text: "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.", category: "fear", reference: "2 Timothy 1:7", tags: ["fear", "kjv"] },
  { text: "Fear thou not; for I [am] with thee: be not dismayed; for I [am] thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.", category: "fear", reference: "Isaiah 41:10", tags: ["fear", "kjv"] },
  { text: "For I the LORD thy God will hold thy right hand, saying unto thee, Fear not; I will help thee.", category: "fear", reference: "Isaiah 41:13", tags: ["fear", "kjv"] },
  { text: "But now thus saith the LORD that created thee, O Jacob, and he that formed thee, O Israel, Fear not: for I have redeemed thee, I have called [thee] by thy name; thou [art] mine.", category: "fear", reference: "Isaiah 43:1", tags: ["fear", "kjv"] },
  { text: "Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he [it is] that doth go with thee; he will not fail thee, nor forsake thee.", category: "fear", reference: "Deuteronomy 31:6", tags: ["fear", "kjv"] },
  { text: "And the LORD, he [it is] that doth go before thee; he will be with thee, he will not fail thee, neither forsake thee: fear not, neither be dismayed.", category: "fear", reference: "Deuteronomy 31:8", tags: ["fear", "kjv"] },
  { text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou [art] with me; thy rod and thy staff they comfort me.", category: "fear", reference: "Psalm 23:4", tags: ["fear", "kjv"] },
  { text: "Though an host should encamp against me, my heart shall not fear: though war should rise against me, in this [will] I [be] confident.", category: "fear", reference: "Psalm 27:3", tags: ["fear", "kjv"] },
  { text: "The angel of the LORD encampeth round about them that fear him, and delivereth them.", category: "fear", reference: "Psalm 34:7", tags: ["fear", "kjv"] },
  { text: "He shall cover thee with his feathers, and under his wings shalt thou trust: his truth [shall be thy] shield and buckler.", category: "fear", reference: "Psalm 91:4", tags: ["fear", "kjv"] },
  { text: "Thou shalt not be afraid for the terror by night; [nor] for the arrow [that] flieth by day;", category: "fear", reference: "Psalm 91:5", tags: ["fear", "kjv"] },
  { text: "The LORD [is] on my side; I will not fear: what can man do unto me?", category: "fear", reference: "Psalm 118:6", tags: ["fear", "kjv"] },
  { text: "What shall we then say to these things? If God [be] for us, who [can be] against us?", category: "fear", reference: "Romans 8:31", tags: ["fear", "kjv"] },
  { text: "So that we may boldly say, The Lord [is] my helper, and I will not fear what man shall do unto me.", category: "fear", reference: "Hebrews 13:6", tags: ["fear", "kjv"] },
  { text: "There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth is not made perfect in love.", category: "fear", reference: "1 John 4:18", tags: ["fear", "kjv"] },
  { text: "But even the very hairs of your head are all numbered. Fear not therefore: ye are of more value than many sparrows.", category: "fear", reference: "Luke 12:7", tags: ["fear", "kjv"] },
  { text: "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.", category: "peace", reference: "John 14:27", tags: ["peace", "kjv"] },
  { text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.", category: "peace", reference: "Philippians 4:7", tags: ["peace", "kjv"] },
  { text: "And let the peace of God rule in your hearts, to the which also ye are called in one body; and be ye thankful.", category: "peace", reference: "Colossians 3:15", tags: ["peace", "kjv"] },
  { text: "Therefore being justified by faith, we have peace with God through our Lord Jesus Christ:", category: "peace", reference: "Romans 5:1", tags: ["peace", "kjv"] },
  { text: "For to be carnally minded [is] death; but to be spiritually minded [is] life and peace.", category: "peace", reference: "Romans 8:6", tags: ["peace", "kjv"] },
  { text: "I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.", category: "peace", reference: "Psalm 4:8", tags: ["peace", "kjv"] },
  { text: "Depart from evil, and do good; seek peace, and pursue it.", category: "peace", reference: "Psalm 34:14", tags: ["peace", "kjv"] },
  { text: "Great peace have they which love thy law: and nothing shall offend them.", category: "peace", reference: "Psalm 119:165", tags: ["peace", "kjv"] },
  { text: "And the work of righteousness shall be peace; and the effect of righteousness quietness and assurance for ever.", category: "peace", reference: "Isaiah 32:17", tags: ["peace", "kjv"] },
  { text: "For the mountains shall depart, and the hills be removed; but my kindness shall not depart from thee, neither shall the covenant of my peace be removed, saith the LORD that hath mercy on thee.", category: "peace", reference: "Isaiah 54:10", tags: ["peace", "kjv"] },
  { text: "The LORD lift up his countenance upon thee, and give thee peace.", category: "peace", reference: "Numbers 6:26", tags: ["peace", "kjv"] },
  { text: "Now the Lord of peace himself give you peace always by all means. The Lord [be] with you all.", category: "peace", reference: "2 Thessalonians 3:16", tags: ["peace", "kjv"] },
  { text: "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.", category: "peace", reference: "John 16:33", tags: ["peace", "kjv"] },
  { text: "For he is our peace, who hath made both one, and hath broken down the middle wall of partition [between us];", category: "peace", reference: "Ephesians 2:14", tags: ["peace", "kjv"] },
  { text: "And the fruit of righteousness is sown in peace of them that make peace.", category: "peace", reference: "James 3:18", tags: ["peace", "kjv"] },
  { text: "Now the God of peace [be] with you all. Amen.", category: "peace", reference: "Romans 15:33", tags: ["peace", "kjv"] },
  { text: "For God is not [the author] of confusion, but of peace, as in all churches of the saints.", category: "peace", reference: "1 Corinthians 14:33", tags: ["peace", "kjv"] },
];

export const bibleVersesByCategory = createCategoryIndex(bibleVerses);
