import {
  createCategoryIndex,
  createContentItems,
  type ContentItem,
} from "@/lib/content";

export type PrayerCategory =
  | "anxiety"
  | "healing"
  | "strength"
  | "financial breakthrough"
  | "guidance"
  | "protection"
  | "gratitude";

const prayersByCategory: Record<PrayerCategory, string[]> = {
  anxiety: [
    "Lord, my thoughts feel louder than my faith right now. Quiet what is racing in me and help me breathe with trust again.",
    "God, I bring You the worry I have been carrying in silence. Remind me that I do not have to solve everything in one moment.",
    "Father, meet me in this anxious place with calm that is deeper than my circumstances. Help my heart remember that You are near.",
    "Lord, I feel overwhelmed by what I cannot control. Teach me to release the outcome and take only the next faithful step.",
    "God, settle my body, my mind, and my spirit. Let Your peace interrupt every thought that tries to pull me into fear.",
    "Father, I need help choosing trust over panic today. Hold me steady while I learn to rest in Your care.",
    "Lord, when my mind imagines the worst, lead me back to truth. Give me a quiet heart and a clear path forward.",
    "God, I surrender the pressure to understand every detail. Help me believe that Your wisdom is working even here.",
    "Father, calm the places in me that feel unsafe. Surround me with Your presence and remind me that I am not alone.",
    "Lord, I give You the fear beneath my overthinking. Replace it with courage, patience, and peace for this day.",
    "God, help me stop rehearsing problems and start remembering Your faithfulness. Let my thoughts become softer and more hopeful.",
    "Father, I am tired from carrying tomorrow too early. Bring me back to today and give me enough grace for this moment.",
    "Lord, steady my breathing and quiet my spirit. I receive Your help one breath, one thought, and one step at a time.",
    "God, when anxiety rises, teach me to pause before I spiral. Let prayer become my first response instead of my last resort.",
    "Father, I lay down the weight of imagined outcomes. Help me trust that You are already present in what I have not reached yet.",
    "Lord, hold the parts of me that feel fragile. Give me peace that does not depend on everything being perfect.",
    "God, I need Your comfort in the middle of uncertainty. Remind me that I can be honest, afraid, and still held by You.",
    "Father, turn my anxious energy into wise action. Show me what to release, what to handle, and what to trust You with.",
  ],
  healing: [
    "Lord, touch the places in me that still hurt. Bring healing to my heart, my memories, my body, and my spirit.",
    "God, I invite You into the wounds I have tried to hide. Restore what pain distorted and help me receive wholeness again.",
    "Father, heal me gently where I am tender and deeply where I am tired. Teach me how to care for myself without shame.",
    "Lord, I release the bitterness that has been protecting my pain. Give me freedom that feels safe, honest, and lasting.",
    "God, restore what was broken in me with Your love and truth. Let this season become a place of renewal, not defeat.",
    "Father, I need healing that reaches beneath the surface. Bring light to old grief and strength to the parts of me still recovering.",
    "Lord, help me forgive at the pace You lead me. Free my heart from carrying what You never asked me to keep.",
    "God, bring peace to my body and rest to my mind. Let Your presence become medicine for the places that ache.",
    "Father, I am ready to stop surviving the same wound over and over. Lead me into restoration with courage and compassion.",
    "Lord, heal the way I see myself after what I have been through. Remind me that pain is part of my story, not my identity.",
    "God, give me patience with the healing process. Help me notice every small sign of strength returning.",
    "Father, make my heart whole without making it hard. Let love, wisdom, and peace grow where fear used to live.",
    "Lord, I bring You the disappointment I do not always know how to name. Meet me with comfort and rebuild my hope.",
    "God, heal my thoughts from shame and my spirit from weariness. Help me walk forward lighter than before.",
    "Father, let Your grace reach the places words cannot explain. Restore my joy and teach me to trust life again.",
    "Lord, thank You for staying near while I recover. Give me the courage to keep choosing healing one day at a time.",
    "God, renew my strength from the inside out. Let restoration become visible in my peace, my choices, and my relationships.",
  ],
  strength: [
    "Lord, I feel weak, but I know You are strong. Give me courage for what is in front of me today.",
    "God, strengthen my heart when the road feels long. Help me keep going with faith, wisdom, and steady hope.",
    "Father, I need endurance that does not come from pressure. Fill me with strength that is rooted in Your presence.",
    "Lord, help me stand when I want to quit. Remind me that I can do hard things with You beside me.",
    "God, renew the parts of me that feel exhausted. Give me a fresh spirit and a steady mind.",
    "Father, teach me the difference between forcing and persevering. Help me move with grace, not with burnout.",
    "Lord, give me strength to obey what I already know is right. Help me choose faithfulness even when it is uncomfortable.",
    "God, I need courage for the conversation, the decision, and the next step. Go before me and steady me.",
    "Father, strengthen my discipline without making my heart harsh. Let wisdom and compassion guide my effort.",
    "Lord, when I feel stretched beyond myself, remind me that Your grace is enough. Help me lean on You without shame.",
    "God, build resilience in me through this season. Let pressure produce maturity, not bitterness.",
    "Father, give me strength to keep my peace and protect my purpose. Help me respond from truth instead of exhaustion.",
    "Lord, help me rise today with a willing heart. Give me power to finish what matters and release what does not.",
    "God, strengthen my faith where disappointment made it tired. Teach me to hope again with open hands.",
    "Father, I receive strength for the work, patience for the process, and courage for the unknown. Stay close as I move forward.",
    "Lord, help me carry responsibility without carrying fear. Give me wisdom, stamina, and a calm spirit.",
    "God, make me stronger in the quiet places no one sees. Let my private growth prepare me for public purpose.",
  ],
  "financial breakthrough": [
    "Lord, bring wisdom, order, and opportunity into my financial life. Help me steward what I have while trusting You for increase.",
    "God, I ask for provision with humility and faith. Open doors that align with purpose, integrity, and peace.",
    "Father, help me break old patterns of fear, avoidance, and scarcity. Teach me to manage money with clarity and courage.",
    "Lord, guide my decisions around work, spending, saving, and giving. Let my finances become peaceful, disciplined, and fruitful.",
    "God, provide for every real need and show me the next wise step. Help me recognize opportunity when it arrives.",
    "Father, I surrender financial stress to You today. Replace panic with a plan and shame with wisdom.",
    "Lord, bless the work of my hands and the ideas You have placed in me. Help me create value and receive value with gratitude.",
    "God, open the right doors and close the ones that would cost my peace. Lead me into provision that does not pull me away from You.",
    "Father, help me become faithful with little and wise with more. Prepare my character for the increase I am praying for.",
    "Lord, give me courage to face my finances honestly. Show me where to adjust, where to ask for help, and where to trust You.",
    "God, release creative solutions and aligned opportunities. Help me move from lack-minded fear into disciplined expectation.",
    "Father, I pray for breakthrough that also brings maturity. Let provision grow alongside stewardship and generosity.",
    "Lord, remove confusion from my financial decisions. Give me clear priorities, wise counsel, and consistent follow-through.",
    "God, help me honor You with my resources. Let money become a tool for stability, service, and freedom.",
    "Father, meet me in the pressure of bills, goals, and responsibilities. Provide what I need and teach me how to build wisely.",
    "Lord, I trust You as my Source beyond every resource. Help me work faithfully and receive provision without fear.",
    "God, turn financial strain into a place of learning and breakthrough. Lead me into peace, order, and overflow with purpose.",
  ],
  guidance: [
    "Lord, I need Your direction more than my own assumptions. Make the next right step clear and give me courage to take it.",
    "God, guide my thoughts, choices, and timing today. Help me recognize peace, wisdom, and warning when they appear.",
    "Father, I surrender the need to rush ahead. Lead me at the pace of Your wisdom.",
    "Lord, open my eyes to the path that honors You and protects my peace. Close the doors that are not meant for me.",
    "God, help me make decisions from clarity instead of fear. Let truth be louder than pressure.",
    "Father, if I am missing something, reveal it gently and clearly. Give me ears to hear and a heart willing to obey.",
    "Lord, guide my relationships, responsibilities, and opportunities. Help me choose what is fruitful, faithful, and wise.",
    "God, I do not want to be led by pride, panic, or comparison. Lead me by peace, purpose, and truth.",
    "Father, show me what to keep, what to release, and what to wait on. I trust You with the timing.",
    "Lord, give me wisdom for the decision I have been avoiding. Help me move forward without confusion.",
    "God, order my steps and redirect me when I drift. Let my life stay aligned with Your purpose.",
    "Father, teach me to notice the quiet guidance I often overlook. Help me follow the light I already have.",
    "Lord, guide my words before I speak and my actions before I move. Let my choices carry grace and wisdom.",
    "God, make the next season clearer as I walk with You. I trust that You can lead me one step at a time.",
    "Father, remove distractions that make Your direction hard to hear. Bring my attention back to what matters.",
    "Lord, help me discern between a good option and the right assignment. Lead me into what bears lasting fruit.",
    "God, I place this decision in Your hands. Give me peace when to move, patience when to wait, and courage when to act.",
  ],
  protection: [
    "Lord, cover me and the people I love today. Guard our hearts, minds, bodies, and steps.",
    "God, protect me from harm I can see and harm I cannot see. Surround me with wisdom, peace, and Your presence.",
    "Father, keep me from choices that would pull me away from purpose. Help me recognize danger before I step into it.",
    "Lord, protect my mind from fear and my heart from bitterness. Let Your truth be a shield around me.",
    "God, watch over my home, my work, my travel, and my relationships. Keep what concerns me under Your care.",
    "Father, protect my peace from unnecessary conflict and confusion. Teach me when to speak, when to wait, and when to walk away.",
    "Lord, guard the doors of my life. Let nothing enter that is not aligned with Your wisdom.",
    "God, protect me from discouragement that tries to make me quit. Keep my spirit steady and my hope alive.",
    "Father, cover my family with grace, safety, and discernment. Lead each of us away from harm and toward peace.",
    "Lord, protect my purpose from distraction and delay. Help me stay faithful to what You have assigned to me.",
    "God, place the right people around me and remove what is not healthy. Give me wisdom to notice the difference.",
    "Father, protect my heart as I heal and grow. Let me stay open without becoming careless.",
    "Lord, keep me safe in moments of pressure and uncertainty. Remind me that I am not walking alone.",
    "God, protect my thoughts from lies and my decisions from fear. Let truth guide every step.",
    "Father, cover this day before I enter it fully. Go before me, walk beside me, and bring me through with peace.",
    "Lord, protect my energy from what drains my spirit without purpose. Help me honor healthy boundaries.",
    "God, be my refuge when life feels unpredictable. Keep me grounded, guarded, and guided by Your love.",
  ],
  gratitude: [
    "Lord, thank You for the breath in my body and the grace over my life. Help me notice the blessings I often move past too quickly.",
    "God, I am grateful for every quiet mercy that carried me here. Teach me to live with open eyes and a thankful heart.",
    "Father, thank You for provision, protection, and the chance to begin again. Let gratitude shape the way I see this day.",
    "Lord, I thank You for the lessons that made me wiser and the grace that kept me soft. Help me honor both.",
    "God, thank You for meeting needs I knew about and needs I never saw. Make me mindful of Your faithfulness.",
    "Father, I am grateful for growth, even when it came through challenge. Help me receive the fruit without resenting the process.",
    "Lord, thank You for people who love me, correct me, and pray for me. Help me become that kind of blessing to others.",
    "God, I thank You for peace that returns, hope that rises, and strength that shows up. Let my life become a response of gratitude.",
    "Father, thank You for doors You opened and doors You closed. Help me trust Your wisdom in both.",
    "Lord, I am grateful for small beginnings and quiet progress. Teach me not to despise what You are growing slowly.",
    "God, thank You for being present in ordinary moments. Help me find joy in simple gifts today.",
    "Father, I thank You for forgiveness, patience, and another chance to choose well. Let gratitude keep my heart humble.",
    "Lord, thank You for carrying me through days I did not know how to handle. Help me remember Your faithfulness when new challenges come.",
    "God, I am grateful for the strength to keep going. Let my thankfulness become courage for the next step.",
    "Father, thank You for every lesson, resource, relationship, and opportunity in my life. Help me steward them with love.",
    "Lord, I receive this day as a gift, not a burden. Teach me to move through it with gratitude and grace.",
    "God, thank You for loving me before I had everything figured out. Let that truth make me gentle, joyful, and generous.",
  ],
};

export const prayers = createContentItems(prayersByCategory, [
  "prayer",
  "devotional",
]) as ContentItem[];

export const prayersByCategoryIndex = createCategoryIndex(prayers);
